### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by gaveer** [FabysGames/mythicplustimer#16]
Hello there @fabysdev @FabysGames 
i have issue with the minimap related to the addon MPT 
when ever i start any Mythic + key the map disappear , i saw in configs there is option to hide tracker
i have `ObjectiveTrackerFrame` on **Hide**
- Version 1.4.4
- Recorde
 " https://www.gifyourgame.com/LaicSternmostBarry

**Comment by fabysdev** [comment]
Sorry for the late reply, i was not active in WoW.

There must be an addon that sets the parent frame of the minimap and the default object tracker to the same. MythicPlusTimer hides the parent frame of the default object tracker because otherwise Quest Tracker addons will not be hidden. 
See https://github.com/FabysGames/mythicplustimer/pull/6

Maybe you can send your addon list?

**Comment by gaveer** [comment]
![image](https://user-images.githubusercontent.com/45834601/174448034-9089db54-61b7-4dc5-b867-66130fec2373.png)
![image](https://user-images.githubusercontent.com/45834601/174448042-5e09faad-e1b0-4f54-8e11-6807a8a2689a.png)
![image](https://user-images.githubusercontent.com/45834601/174448048-f5b2f76d-8419-4805-b4ff-fbbb6eefb1ba.png)
![image](https://user-images.githubusercontent.com/45834601/174448066-d9bf107a-070b-489f-9413-c6762b431663.png)

**Comment by gaveer** [comment]
might be **fixed**

**Comment by fabysdev** [comment]
i could not reproduce the bug ... maybe reopen if you find the incompatible addon thanks
