### ISSUE TITLE
doesn't work after update, version 11.0.0

### ISSUE THREAD

**Issue by exz00** [FabysGames/mythicplustimer#39]
timer, trash %, boss count etc, just doesn't work after 11.0.0 update

**Comment by ivankprod** [comment]
same issue

**Comment by R41z0r** [comment]
Linking https://github.com/FabysGames/mythicplustimer/issues/38

**Comment by malbaratar** [comment]
Same issue. Timer doesn't start after putting in key, just stays at dungeon start value. Mob percentage also doesn't update

**Comment by fabysdev** [comment]
The  6.0.0 (11.0) version ist not compatible with the 10.2 WoW client. Please use the older 5.x version for the 10.X client. 

The 6.0.0 is marked to only work with the 11.0 version, please check your updater to correctly download the supported version for 10.X.

I hope addon updater do this check automatically otherwise the whole version marking is useless. Please report if changing a setting in your updater works, otherwise i need to withdraw the 6.0.0 verison for now.

**Comment by R41z0r** [comment]
Version marking is just for compatability, there is no "don't download 11 when I have 10"

**Comment by fabysdev** [comment]
> Version marking is just for compatability, there is no "don't download 11 when I have 10"

but there should be, don't download 11 if it is not compatible with the installed client?

**Comment by R41z0r** [comment]
> > Version marking is just for compatability, there is no "don't download 11 when I have 10"
> 
> but there should be, don't download 11 if it is not compatible with the installed client?

Another person wrote in #38 this:

Curseforge doesn't have the ability to only have addons for PTR, only for Retail/Classic flavors. Releasing a 11.x only addon right now will break retail

**Comment by fabysdev** [comment]
I switched the new version to be flagged as beta this morning, should all be good now i hope.

i keep this issue open for visibilty until the release

**Comment by fabysdev** [comment]
A version for 11.0 is on the release track again
